In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

print(tf.__version__)

2.12.0


In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = layers.RNN(cell, return_sequences=True, return_state=True) # analogous to tf.nn.dynamic_rnn
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.33694917 0.6071421 ]]], shape: (1, 1, 2)
states: [[0.33694917 0.6071421 ]], shape: (1, 2)


In [4]:
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,
                       return_state=True) # layers.SimpleRNNCell + layers.RNN

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[ 0.6020519 -0.6071489]]], shape: (1, 1, 2)
states: [[ 0.6020519 -0.6071489]], shape: (1, 2)


In [5]:
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.23884071 -0.02342892]
  [-0.02056094  0.10196883]
  [ 0.361839   -0.5702062 ]
  [-0.19204068 -0.12827489]
  [ 0.7535214  -0.3700941 ]]], shape: (1, 5, 2) 

states: [[ 0.7535214 -0.3700941]], shape: (1, 2)


In [6]:
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)    
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[ 0.51398975  0.48525387]
  [ 0.8055049  -0.53153074]
  [-0.5559815  -0.9246341 ]
  [-0.8760691  -0.38543445]
  [-0.87779444  0.21344005]]

 [[ 0.47188416 -0.21761902]
  [-0.6939832  -0.77868384]
  [-0.8492003  -0.23114082]
  [-0.6436906   0.05599654]
  [-0.4086219  -0.06816018]]

 [[-0.3110401  -0.60725474]
  [-0.75681    -0.50873715]
  [-0.17279918  0.36137596]
  [ 0.6733972   0.0391464 ]
  [-0.1094095  -0.8728596 ]]], shape: (3, 5, 2) 

states: [[-0.87779444  0.21344005]
 [-0.4086219  -0.06816018]
 [-0.1094095  -0.8728596 ]], shape: (3, 2)
