In [1]:
import tensorflow as tf
import numpy as np

In [5]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]
# y_data : one-hot encoded (특정 분류에 대해서만 1로 표현하고 나머지는 0으로 표현)

x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

nb_classes = 3

In [9]:
W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

In [10]:
def hypothesis(X):
  return tf.nn.softmax(tf.matmul(X, W) + b)

In [12]:
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype = np.float32)

print(hypothesis(sample_db))

tf.Tensor([[2.0169767e-03 1.6138420e-06 9.9798143e-01]], shape=(1, 3), dtype=float32)


In [14]:
def cost_fn(X, Y):
  logits = hypothesis(X)
  cost = -tf.reduce_sum(Y * tf.math.log(logits), axis = 1)
  cost_mean = tf.reduce_mean(cost)
  return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(4.0656147, shape=(), dtype=float32)


In [16]:
def grad_fn(X, Y):
  with tf.GradientTape() as tape:
    loss = cost_fn(X, Y)
    grads = tape.gradient(loss, variables) # variables : [W, b]
    return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.14898476,  0.50833726, -0.35935262],
       [-1.590442  ,  1.7897184 , -0.19927667],
       [-1.5016623 ,  1.9649178 , -0.46325597],
       [-1.5008495 ,  1.8939719 , -0.3931229 ]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.21688034,  0.39348856, -0.17660828], dtype=float32)>]


In [19]:
def fit(X, Y, epochs = 2000, verbose = 100):
  optimizer = tf.keras.optimizers.SGD(learning_rate = 0.1)
  for i in range(epochs):
    grads = grad_fn(X, Y)
    optimizer.apply_gradients(zip(grads, variables))
    if (i == 0) | ((i + 1) % verbose == 0):
      print("Loss at epoch %d : %f" %(i + 1, cost_fn(X, Y).numpy()))

fit(x_data, y_data)

Loss at epoch 1 : 0.088446
Loss at epoch 100 : 0.086678
Loss at epoch 200 : 0.084961
Loss at epoch 300 : 0.083309
Loss at epoch 400 : 0.081718
Loss at epoch 500 : 0.080186
Loss at epoch 600 : 0.078709
Loss at epoch 700 : 0.077284
Loss at epoch 800 : 0.075909
Loss at epoch 900 : 0.074582
Loss at epoch 1000 : 0.073298
Loss at epoch 1100 : 0.072058
Loss at epoch 1200 : 0.070858
Loss at epoch 1300 : 0.069696
Loss at epoch 1400 : 0.068572
Loss at epoch 1500 : 0.067482
Loss at epoch 1600 : 0.066426
Loss at epoch 1700 : 0.065401
Loss at epoch 1800 : 0.064408
Loss at epoch 1900 : 0.063443
Loss at epoch 2000 : 0.062507


In [21]:
a = hypothesis(x_data)

print(a)
print(tf.argmax(a, 1))
print(tf.argmax(y_data, 1)) #예측값과 실제 y_data가 같은지 확인할 수 있음.

tf.Tensor(
[[2.3260516e-09 4.2413525e-05 9.9995750e-01]
 [3.8641106e-04 3.0960310e-02 9.6865320e-01]
 [2.4430426e-11 6.5454721e-02 9.3454522e-01]
 [3.2255883e-08 9.4103754e-01 5.8962490e-02]
 [1.1157170e-01 8.8389146e-01 4.5366939e-03]
 [5.9106592e-02 9.4089174e-01 1.6439121e-06]
 [8.7074101e-01 1.2925795e-01 9.7176064e-07]
 [9.8320526e-01 1.6794756e-02 2.0224826e-09]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
