In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Model

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [7]:
# One cell RNN input_dim (4) -> output_dim (2 : hidden size)
x_data = np.array([[h]], dtype=np.float32)

hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size) # creating SimpleRNNCell
rnn = layers.RNN(cell, return_sequences=True, return_state=True) # analogous to tf.nn.dynamic_rnn
outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[-0.7443333  -0.62206656]]], shape: (1, 1, 2)
states: [[-0.7443333  -0.62206656]], shape: (1, 2)


In [8]:
# equivalent to above case
rnn = layers.SimpleRNN(units=hidden_size, return_sequences=True,
                       return_state=True) # layers.SimpleRNNCell + layers.RNN

outputs, states = rnn(x_data)

print('x_data: {}, shape: {}'.format(x_data, x_data.shape))
print('outputs: {}, shape: {}'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
outputs: [[[0.0552299  0.11827682]]], shape: (1, 1, 2)
states: [[0.0552299  0.11827682]], shape: (1, 2)


In [9]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4) 

outputs: [[[ 0.55751115 -0.03657092]
  [-0.09109628 -0.07576436]
  [-0.6083758  -0.42523402]
  [-0.82363915 -0.70352316]
  [-0.75052005 -0.93014526]]], shape: (1, 5, 2) 

states: [[-0.75052005 -0.93014526]], shape: (1, 2)


In [10]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
rnn = layers.SimpleRNN(units=2, return_sequences=True, return_state=True)
outputs, states = rnn(x_data)

print('x_data: {}, shape: {} \n'.format(x_data, x_data.shape))
print('outputs: {}, shape: {} \n'.format(outputs, outputs.shape))
print('states: {}, shape: {}'.format(states, states.shape))

x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4) 

outputs: [[[-0.43417448  0.41595027]
  [-0.5818318  -0.44527537]
  [-0.7707082   0.11932323]
  [-0.917547    0.33180118]
  [-0.8699358  -0.9001201 ]]

 [[-0.06666034 -0.39764106]
  [-0.22122698 -0.8625922 ]
  [-0.4386336   0.12058377]
  [-0.8758604   0.535225  ]
  [-0.9608736   0.49020016]]

 [[-0.753182    0.6917826 ]
  [-0.9637351   0.6239332 ]
  [-0.823701   -0.63195604]
  [-0.12409838 -0.8971502 ]
  [-0.363578    0.17059416]]], shape: (3, 5, 2) 

states: [[-0.8699358  -0.9001201 ]
 [-0.9608736   0.49020016]
 [-0.363578    0.17059416]], shape: (3, 2)


states 변수 안에는 각 mini-batch들의 마지막 결과값들을 모아두었음.